### ISSUE TITLE
/dev/random AAS exists!

### ISSUE THREAD

**Issue by jomo** [noqqe/devnull-as-a-service#20]
From your Features page:
> **Upcoming**
/dev/random as a Service: Do you think every random-number-generator is broken? Well, we do! Simply trust us and use our numbers as your only seeding source!

Here is your [`/dev/random`](https://www.random.org/clients/http/) service.

Also:
> /dev/null for Bitcoin - Nullify your Bitcoins and amaze your friends! The most secure Bitcoin endpoint yet!

This has already been done by the blockchain.info Android app *using random.org*, sorta. [Read this](https://www.reddit.com/r/Bitcoin/comments/37oxow/the_security_issue_of_blockchaininfos_android/crolfk4) for details.

----

Just wanted to let you know, thanks for this useful service!

**Comment by noqqe** [comment]
Great! Thanks!
