### ISSUE TITLE
Why does http://devnull-as-a-service.com/dev/null return cookies?

### ISSUE THREAD

**Issue by R3D4C73D** [noqqe/devnull-as-a-service#24]
POST http://devnull-as-a-service.com/dev/null returns two cookies.  _pk_id.7.7d76 and _pk_ses.7.7d76.  Why?

**Comment by noqqe** [comment]
It does not. Try:

```
curl -c - -X POST 'https://devnull-as-a-service.com/dev/null'
```

What did you use for the test?

**Comment by noqqe** [comment]
no response...

**Comment by JayAndCatchFire** [comment]
Sorry, it must have been something about my browser.  I tried it again and no cookies were returned.
