### ISSUE TITLE
What is the LICENSE?

### ISSUE THREAD

**Issue by sumnerevans** [noqqe/devnull-as-a-service#31]
My business wants to extend on your amazing work in secure deletion of files. We would like to use your code, but only if it's under a very non-permissive license. Some good examples of licenses that would work for us are:

- The old Facebook ReactJS non-compete license
- University of Utah Public License
- Apple Public Source License v1.x
- AT&T Public License
- The JSON License
- The Occulus Rift License
- TrueCrypt License 3.0

**Comment by noqqe** [comment]
Will implement! :)
